# molecule/default/prepare.yml
---
- name: Prepare test host
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      register: apt_cache_update
      when: ansible_os_family == "Debian"
