# molecule/default/verify.yml
---
- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run pytest
      delegate_to: localhost
      ansible.builtin.command:
        cmd: pytest --connection=docker --hosts=instance molecule/default/tests
      changed_when: false
